PACKAGE = foxandhounds.logic

SOURCE  = \
	Coordinates.java \
	Experiment.java \
	Fox.java \
	Play.java \
	Hounds.java \
	LearningSystem.java \
	State.java \

RMI_SOURCE =

MAIN       = Experiment

include $(JAVA_DEV_ROOT)/Makefile
