PACKAGE = foxandhounds.logic

SOURCE  = \
	Coordinates.java \
	Fox.java \
	Play.java \
	Hounds.java \
	LearningSystem.java \
	State.java \

RMI_SOURCE =

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
