PACKAGE = foxandhounds.gui

SOURCE  = \
	BoardPanel.java \
	ControlPanel.java \
	Piece.java \
	LearningSystemInfo.java \
	MainFrame.java \
	Main.java \
	dog-icon.jpg \
	fox-icon.jpg \

RMI_SOURCE =

MAIN       = Main

include $(JAVA_DEV_ROOT)/Makefile
